import cookieParser from 'cookie-parser';
import compression from 'compression';
import cors from 'cors';
import express, { type Application, type NextFunction, type Request, type Response } from 'express';
import helmet from 'helmet';
import * as Sentry from '@sentry/node';
import { validateCsrfToken, generateCsrfToken } from './middlewares/csrfMiddleware';
import { authMiddleware } from './middlewares/authMiddleware';
import { sendError } from './lib/response';
import { logger } from './logger';
import { createRateLimiter } from './lib/rateLimiter';
import { authRouter, createInternalRouter } from './routes/auth';
import { filesRouter } from './routes/files';
import { foldersRouter } from './routes/folders';
import { shareRouter } from './routes/share';
import { imagesRouter } from './routes/images';
import roomRoutes from './routes/roomRoutes';

if (process.env.SENTRY_DSN) {
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    environment: process.env.NODE_ENV || 'development',
  });
}

export const generalRateLimit = createRateLimiter({
  limit: 250,
  windowMs: 15 * 60 * 1000,
  prefix: 'dripl:http:general',
});

const authRateLimit = createRateLimiter({
  limit: 10,
  windowMs: 15 * 60 * 1000,
  prefix: 'dripl:http:auth',
});

function setRetryAfter(res: Response, resetAt: number): void {
  res.setHeader('Retry-After', String(Math.max(1, Math.ceil((resetAt - Date.now()) / 1000))));
}

/**
 * `body-parser` marks its rejections with a `type` drawn from this fixed list
 * (`json.js` / `urlencoded.js` / `read.js`), which is a far more stable
 * contract than the message text — those are generated by V8 and by `http-errors`
 * and are not part of any published API.
 */
const BODY_PARSER_CLIENT_ERROR_TYPES = new Set([
  'entity.parse.failed',
  'entity.too.large',
  'entity.verify.failed',
  'request.aborted',
  'request.size.invalid',
  'charset.unsupported',
  'encoding.unsupported',
  'parameters.too.many',
]);

/** The `Error` this module's own CORS `origin` callback rejects with. */
const CORS_REJECTION_PREFIX = 'CORS: origin ';

type OperationalErrorKind = 'body_parser' | 'cors_origin';

/**
 * Recognise an error a client caused. Deliberately matches on an explicit
 * marker rather than on "the error carries a 4xx status": a service-layer
 * exception that happens to carry `status: 403` is still a bug in this process,
 * and a status-code sniff would quietly relabel it as the caller's fault.
 *
 * Returns null for everything else, which includes every throw from a route,
 * service, Prisma query, or storage driver — those stay programmer errors.
 */
function classifyOperationalError(error: Error): { kind: OperationalErrorKind } | null {
  const type = (error as { type?: unknown }).type;
  if (typeof type === 'string' && BODY_PARSER_CLIENT_ERROR_TYPES.has(type)) {
    return { kind: 'body_parser' };
  }
  if (error.message.startsWith(CORS_REJECTION_PREFIX)) {
    return { kind: 'cors_origin' };
  }
  return null;
}

export async function rateLimitMiddleware(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  // `/live` joins `/health` and `/metrics` as exempt: all three are probed from
  // outside the app (a supervisor, a scrape), so charging the probe against a
  // per-IP budget would let a health check exhaust a caller's rate limit.
  if (req.path === '/live' || req.path === '/health' || req.path === '/metrics') {
    next();
    return;
  }
  const identifier =
    (req as Request & { session?: { userId?: string } }).session?.userId ?? req.ip ?? 'anonymous';
  const { success, remaining, resetAt } = await generalRateLimit.limit(identifier);
  if (!success) {
    setRetryAfter(res, resetAt);
    sendError(res, 429, 'RATE_LIMITED', 'Rate limit exceeded');
    return;
  }
  res.setHeader('X-RateLimit-Remaining', remaining);
  next();
}

export async function authRateLimitMiddleware(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  const identifier = req.ip ?? 'anonymous';
  const { success, resetAt } = await authRateLimit.limit(identifier);
  if (!success) {
    setRetryAfter(res, resetAt);
    sendError(res, 429, 'RATE_LIMITED', 'Too many attempts, please try again later.');
    return;
  }
  next();
}

export function createApp(): Application {
  const app = express();

  // Liveness, deliberately distinct from the readiness probe below. It answers
  // exactly one question — is this event loop still turning — and performs no
  // I/O, so it cannot fail for a reason that restarting the process would fix.
  // `/health` is the opposite: it is a *readiness* probe, because it requires
  // Postgres and answers 503 when the database is unreachable. A supervisor
  // whose restart policy watches `/health` conflates the two, and the
  // difference is not latency but availability of the whole service: a
  // 60-second Postgres blip takes every API down with it even though this
  // process is perfectly able to answer as soon as the database returns.
  app.get('/live', (_req, res) => {
    res.status(200).json({ status: 'ok', uptime: process.uptime(), ts: Date.now() });
  });

  app.get('/health', async (_req, res) => {
    try {
      const { db } = await import('@dripl/db');
      await db.$queryRaw`SELECT 1`;
      res.status(200).json({
        status: 'ok',
        uptime: process.uptime(),
        memoryMB: Math.round(process.memoryUsage().heapUsed / 1024 / 1024),
        ts: Date.now(),
      });
    } catch {
      res.status(503).json({ status: 'error', message: 'Database unreachable', ts: Date.now() });
    }
  });

  app.set('trust proxy', process.env.TRUST_PROXY === 'true' ? 1 : false);
  app.use(helmet());
  app.use(compression());
  app.use(rateLimitMiddleware);

  const normalizeOrigin = (value: string | undefined): string | null => {
    if (!value) return null;
    try {
      const parsed = new URL(value);
      if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return null;
      return parsed.origin;
    } catch {
      return null;
    }
  };
  const allowedOrigins = [process.env.FRONTEND_URL, process.env.NEXT_PUBLIC_APP_URL]
    .flatMap(value => value?.split(',') ?? [])
    .map(normalizeOrigin)
    .filter((value): value is string => value !== null);

  if (process.env.NODE_ENV !== 'production' && !allowedOrigins.includes('http://localhost:3000')) {
    allowedOrigins.push('http://localhost:3000');
  }

  app.use(
    cors({
      origin: (origin, callback) => {
        if (!origin || allowedOrigins.some(o => origin === o)) {
          callback(null, true);
        } else {
          callback(new Error(`CORS: origin ${origin} not allowed`));
        }
      },
      credentials: true,
      methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
      allowedHeaders: ['Content-Type', 'Authorization', 'x-csrf-token'],
    })
  );
  app.use(express.json({ limit: '5mb' }));
  app.use(express.urlencoded({ extended: true, limit: '5mb' }));
  app.use(cookieParser());

  app.get('/', (_req, res) => {
    res.json({ service: 'dripl-http', status: 'ok' });
  });

  app.get('/metrics', (_req, res) => {
    res.json({
      uptime: process.uptime(),
      memoryUsageMB: Math.round(process.memoryUsage().heapUsed / 1024 / 1024),
    });
  });

  app.get('/csrf-token', (_req, res) => {
    const token = generateCsrfToken(res);
    res.json({ token });
  });

  app.use('/api/auth/login', validateCsrfToken);
  app.use('/api/auth/forgot-password', validateCsrfToken);
  app.use('/api/auth/register', validateCsrfToken);
  app.use('/api/auth/reset-password', validateCsrfToken);
  app.use('/api/auth/change-password', validateCsrfToken);
  app.use('/api/auth/logout', validateCsrfToken);
  app.use('/api/auth/ws-ticket', validateCsrfToken);
  app.use('/api/auth/resend-verification', validateCsrfToken);

  app.use('/api/auth/login', authRateLimitMiddleware);
  app.use('/api/auth/forgot-password', authRateLimitMiddleware);
  app.use('/api/auth/register', authRateLimitMiddleware);
  app.use('/api/auth/verify-email', authRateLimitMiddleware);
  app.use('/api/auth/resend-verification', authRateLimitMiddleware);
  app.use('/api/auth', authRouter);
  app.use('/api/share', validateCsrfToken, shareRouter);
  app.use('/api/files', validateCsrfToken, authMiddleware, filesRouter);
  app.use('/api/folders', validateCsrfToken, authMiddleware, foldersRouter);
  // roomRoutes exposes the capability-link GET before its internal auth guard.
  app.use('/api/rooms', validateCsrfToken, roomRoutes);
  // Image uploads require auth at the route; downloads are capability-URL
  // based so shared canvases can render their unguessable image assets.
  app.use('/api/images', validateCsrfToken, imagesRouter);

  app.use('/internal', createInternalRouter());

  Sentry.setupExpressErrorHandler(app);

  app.use((error: Error, req: Request, res: Response, _next: NextFunction) => {
    // Operational error vs programmer error. Anything a *client* can provoke by
    // sending a bad request is not evidence that this server is broken, and
    // logging it at `error` with a stack makes it indistinguishable from a real
    // fault in the one place an incident is triaged from.
    //
    // Three such classes reach here:
    //   - `body-parser` rejects the body it was asked to read and tags the
    //     rejection with a stable `type`. Verified against body-parser@2.3.0:
    //     malformed JSON is `entity.parse.failed`, a body over the 5mb limit is
    //     `entity.too.large`.
    //   - The CORS `origin` callback below raises a plain `Error` for a request
    //     whose `Origin` is not on the allowlist — a cross-origin request from
    //     any page, i.e. attacker-chosen input, with no body or ticket needed.
    //   - `express.urlencoded` raises `parameters.too.many` past its limit.
    //
    // The *response* is deliberately unchanged. `appComposition.test.ts` pins
    // malformed JSON to `500 INTERNAL_ERROR`, and that wire contract is not this
    // module's to renegotiate — this only fixes the classification.
    const operational = classifyOperationalError(error);
    if (operational) {
      logger.warn(
        {
          event: 'http_client_error',
          kind: operational.kind,
          error: error.message,
          method: req.method,
          path: req.originalUrl,
        },
        'Rejected a malformed client request'
      );
    } else {
      logger.error(
        { event: 'http_server_error', error: error.message, stack: error.stack },
        'Unhandled HTTP server error'
      );
    }
    sendError(res, 500, 'INTERNAL_ERROR', 'Internal server error');
  });

  return app;
}
