/**
 * The image storage seam.
 *
 * Two drivers implement this — `filesystemImageStore` and `s3ImageStore` — and
 * the image route talks only to this interface. The filesystem driver stays the
 * default so an existing deployment with no object-storage configuration keeps
 * behaving exactly as it did before; the S3 driver is selected purely by the
 * presence of `IMAGE_S3_BUCKET`.
 *
 * WHY THE INTERFACE IS THIS SMALL. It is the intersection of what the route
 * actually calls today (`writeFile` on upload, `existsSync` + `stat` +
 * `readFile` on download) and nothing else. There is no `list`, no `delete`,
 * no `head`, no multipart upload, no signed-URL minting, no ACL or metadata
 * handling, and no stream type: every method takes and returns a `Buffer`
 * because the route already buffers the whole upload body to validate its magic
 * bytes before it does anything else, so a streaming interface would be a
 * second, differently-shaped code path for zero benefit.
 *
 * `get` returning `null` for "absent" is what removes `exists` and `head` from
 * the interface. The route used `existsSync` to produce a 404 and `stat` only
 * to learn a byte count it was about to overwrite anyway with `buffer.length`,
 * so folding absence into the return value deletes two round trips and one
 * error path without changing a single response.
 *
 * There is deliberately no `delete`. Per-image revocation is a real desire, but
 * it is not reachable from this route, and an unused method on an interface is
 * a promise nobody is keeping. It belongs with the endpoint that will own the
 * permission model, not with the byte-moving seam.
 */

export type ImageStoreKind = 'filesystem' | 's3';

/**
 * Ids are generated by this service. Reject anything outside that narrow
 * format instead of trying to repair a potentially traversal-bearing path.
 *
 * The grammar lives here rather than in the route because every boundary that
 * turns a key into a filesystem path or a URL path segment must apply exactly
 * this check: the route (which owns the security boundary), the filesystem
 * driver (which joins the key onto a directory), the S3 driver (which puts the
 * key in a URL), and the migration script (which reads directory entries off
 * disk and must not upload a `..`-shaped name). One grammar, enforced four
 * times, cannot drift into a path-traversal bug at the boundary nobody
 * remembered.
 */
const IMAGE_KEY_PATTERN = /^[a-f0-9-]+\.(png|jpg|gif|webp)$/i;

/** Message text is part of the route's error contract; do not reword it. */
const INVALID_IMAGE_ID_MESSAGE = 'Invalid image id';

export class InvalidImageKeyError extends Error {
  constructor() {
    super(INVALID_IMAGE_ID_MESSAGE);
    this.name = 'InvalidImageKeyError';
  }
}

export function isImageKey(key: string): boolean {
  return IMAGE_KEY_PATTERN.test(key);
}

/**
 * Validate an image key and return it unchanged, so a caller can write
 * `const key = assertImageKey(raw)` and never touch storage with `raw` itself.
 */
export function assertImageKey(key: string): string {
  if (!isImageKey(key)) {
    throw new InvalidImageKeyError();
  }
  return key;
}

export type ImageStoreErrorCode =
  /** Configuration is missing or self-inconsistent; a restart or a config fix is required. */
  | 'not_configured'
  /** The configured backend could not be reached (DNS, TCP, TLS, timeout). */
  | 'unreachable'
  /** The backend answered, and refused these credentials. */
  | 'forbidden'
  /** The backend answered with a shape or status this driver does not accept. */
  | 'unexpected_response'
  /** Local filesystem I/O failed. */
  | 'local_io';

export interface ImageStoreErrorInit {
  code: ImageStoreErrorCode;
  message: string;
  storeKind: ImageStoreKind;
  /** Whether the same request could plausibly succeed without a config change. */
  retryable?: boolean;
  /** HTTP status, when the failure came from an HTTP response. */
  status?: number | null;
}

/**
 * The single error type every driver raises, so callers can tell "the store is
 * broken" from "this key is not in it" without string matching, and so the
 * image route can report one storage failure mode instead of four.
 */
export class ImageStoreError extends Error {
  readonly code: ImageStoreErrorCode;
  readonly storeKind: ImageStoreKind;
  readonly retryable: boolean;
  readonly status: number | null;

  constructor(init: ImageStoreErrorInit) {
    super(init.message);
    this.name = 'ImageStoreError';
    this.code = init.code;
    this.storeKind = init.storeKind;
    this.retryable = init.retryable ?? false;
    this.status = init.status ?? null;
  }
}

export interface ImageStore {
  readonly kind: ImageStoreKind;
  /**
   * Store `body` under `key`. `key` must already satisfy `isImageKey`; the
   * driver re-validates anyway.
   *
   * `contentType` is the validated request content type, not a client-supplied
   * string: the route has already checked it against its allowlist and against
   * the body's magic bytes. Passing it rather than having the driver derive it
   * from the file extension keeps a single extension-to-MIME mapping in the
   * route, so the two cannot drift apart.
   */
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  /** Read the object, or `null` when the store does not have `key`. */
  get(key: string): Promise<Buffer | null>;
}
