import { z } from 'zod';

export const PointSchema = z.object({
  x: z.number().finite(),
  y: z.number().finite(),
});

export const BindingSchema = z
  .object({
    elementId: z.string(),
    fixedPoint: PointSchema,
    mode: z.enum(['inside', 'orbit']),
  })
  .optional();

export const TextAlignSchema = z.enum(['left', 'center', 'right']);

const ImageSourceSchema = z
  .string()
  .max(2_000_000)
  .refine(value => {
    if (value.startsWith('/')) return !value.startsWith('//');
    if (value.startsWith('data:')) {
      return /^data:image\/(?:png|jpe?g|gif|webp);base64,/i.test(value);
    }
    try {
      const protocol = new URL(value).protocol;
      return protocol === 'https:' || protocol === 'http:';
    } catch {
      return false;
    }
  }, 'Image source must be an HTTP(S), local, or raster data URL');

export const ElementTypeSchema = z.enum([
  'rectangle',
  'ellipse',
  'path',
  'text',
  'image',
  'line',
  'arrow',
  // Specialized element types supported by the editor
  'diamond',
  'freedraw',
  'frame',
  'embed',
]);

export const BaseElementSchema = z.object({
  // Element IDs are generated by several supported clients (and older
  // persisted scenes may use non-UUID IDs), so validate a bounded opaque ID
  // rather than silently dropping a whole scene during import/sync.
  id: z.string().min(1).max(100),
  type: ElementTypeSchema,
  x: z.number().finite().min(-100000).max(100000),
  y: z.number().finite().min(-100000).max(100000),
  width: z.number().finite().min(0).max(50000),
  height: z.number().finite().min(0).max(50000),
  angle: z.number().default(0),
  strokeColor: z.string().max(100).default('#000000'),
  fillColor: z.string().max(100).default('transparent'),
  backgroundColor: z.string().max(100).default('transparent'),
  strokeWidth: z.number().min(0).max(100).default(2),
  opacity: z.number().min(0).max(1).default(1),
  roughness: z.number().min(0).max(2).default(1),
  locked: z.boolean().default(false),
  // Existing fields preserved
  isDeleted: z.boolean().optional(),
  version: z.number().int().nonnegative().optional(),
  versionNonce: z.number().int().nonnegative().optional(),
  updated: z.number().int().nonnegative().optional(),
  createdAt: z.number().int().nonnegative().optional(),
  updatedAt: z.number().int().nonnegative().optional(),
  strokeStyle: z.enum(['solid', 'dashed', 'dotted']).optional(),
  fillStyle: z
    .enum(['hachure', 'solid', 'zigzag', 'cross-hatch', 'dots', 'dashed', 'zigzag-line'])
    .optional(),
  seed: z.number().optional(),
  groupId: z.string().max(100).optional(),
  zIndex: z.number().int().optional(),
  fractionalIndex: z.string().min(1).max(256).optional(),
  rotation: z.number().finite().min(-360).max(360).optional(),
  flipHorizontal: z.union([z.literal(-1), z.literal(1)]).optional(),
  flipVertical: z.union([z.literal(-1), z.literal(1)]).optional(),
  labelId: z.string().max(100).optional(),
  containerId: z.string().max(100).optional(),
  boundElementId: z.string().max(100).optional(),
  /** Hyperlink attached to the element (validated as safe http(s) at the UI/export layers). */
  link: z.string().max(2000).optional(),
  boundElements: z
    .array(
      z.object({
        id: z.string().min(1).max(100),
        type: z.enum(['arrow', 'text']),
      })
    )
    .max(1000)
    .optional(),
});

export const RectangleElementSchema = BaseElementSchema.extend({
  type: z.literal('rectangle'),
});

export const EllipseElementSchema = BaseElementSchema.extend({
  type: z.literal('ellipse'),
});

export const PathElementSchema = BaseElementSchema.extend({
  type: z.literal('path'),
  points: z.array(PointSchema).min(1).max(20000),
});

const LinearStyleShape = {
  arrowStyle: z.enum(['straight', 'curved', 'elbow']).optional(),
  arrowHeads: z
    .object({
      start: z.enum(['triangle', 'dot', 'bar', 'diamond', 'none']).optional(),
      end: z.enum(['triangle', 'dot', 'bar', 'diamond', 'none']).optional(),
    })
    .optional(),
  startBinding: BindingSchema,
  endBinding: BindingSchema,
};

export const LineElementSchema = BaseElementSchema.extend({
  type: z.literal('line'),
  points: z.array(PointSchema).min(2).max(10000),
  ...LinearStyleShape,
});

export const ArrowElementSchema = BaseElementSchema.extend({
  type: z.literal('arrow'),
  points: z.array(PointSchema).min(2).max(10000),
  ...LinearStyleShape,
});

export const TextElementSchema = BaseElementSchema.extend({
  type: z.literal('text'),
  text: z.string().max(10000),
  originalText: z.string().max(10000).optional(),
  fontSize: z.number().finite().min(1).max(500).default(20),
  fontFamily: z.string().max(100).default('Caveat'),
  textAlign: TextAlignSchema.default('left'),
  verticalAlign: z.enum(['top', 'middle', 'bottom']).optional(),
  boundElementId: z.string().max(100).optional(),
  containerId: z.string().max(100).optional(),
});

export const ImageElementSchema = BaseElementSchema.extend({
  type: z.literal('image'),
  dataUrl: ImageSourceSchema.optional(),
  src: ImageSourceSchema.optional(),
  naturalWidth: z.number().finite().positive().optional(),
  naturalHeight: z.number().finite().positive().optional(),
});

const DiamondElementSchema = BaseElementSchema.extend({
  type: z.literal('diamond'),
});

const FreeDrawElementSchema = BaseElementSchema.extend({
  type: z.literal('freedraw'),
  points: z.array(PointSchema).min(1).max(20000),
  brushSize: z.number().finite().min(0).max(100).optional(),
  pressureValues: z.array(z.number().finite().min(0).max(1)).max(20000).optional(),
  widths: z.array(z.number().finite().min(0).max(100)).max(20000).optional(),
});

const FrameElementSchema = BaseElementSchema.extend({
  type: z.literal('frame'),
  title: z.string().max(500).optional(),
  padding: z.number().finite().min(0).max(10000).optional(),
});

const EmbedElementSchema = BaseElementSchema.extend({
  type: z.literal('embed'),
  url: z
    .string()
    .url()
    .max(2048)
    .refine(value => /^https?:$/i.test(new URL(value).protocol), 'Embed URL must use HTTP(S)'),
  title: z.string().max(500).optional(),
  cachedPreview: z.string().max(2_000_000).optional(),
});

export const DriplElementSchema = z.discriminatedUnion('type', [
  RectangleElementSchema,
  EllipseElementSchema,
  PathElementSchema,
  TextElementSchema,
  ImageElementSchema,
  LineElementSchema,
  ArrowElementSchema,
  DiamondElementSchema,
  FreeDrawElementSchema,
  FrameElementSchema,
  EmbedElementSchema,
]);

export const ElementSchema = DriplElementSchema;
export const CanvasContentSchema = z.array(DriplElementSchema);

export const CreateFileSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  folderId: z.string().optional(),
  teamId: z.string().optional(),
});

export const UpdateFileSchema = z.object({
  name: z.string().optional(),
  content: z.string().optional(),
  preview: z.string().optional(),
});

export const FileSchema = z.object({
  id: z.string(),
  name: z.string(),
  content: z.string(),
  preview: z.string().nullable(),
  shareToken: z.string().nullable().optional(),
  sharePermission: z.enum(['view', 'edit']).nullable().optional(),
  shareExpiresAt: z.date().nullable().optional(),
  folderId: z.string().nullable(),
  teamId: z.string().nullable(),
  userId: z.string().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

export type DriplElementSchemaType = z.infer<typeof DriplElementSchema>;
export type ElementType = z.infer<typeof ElementTypeSchema>;
export type CanvasContent = z.infer<typeof CanvasContentSchema>;
export type CreateFileInput = z.infer<typeof CreateFileSchema>;
export type UpdateFileInput = z.infer<typeof UpdateFileSchema>;
